# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Build"
  lane :build do
    gym(scheme: "iOSFirstApp")
  end
  
  desc "Test"
  lane :test do
    scan(
      project: "iOSFirstApp.xcodeproj",
      devices: ["iPhone 6s"]
    )
  end
  
  desc "Test Coverage"
  lane :testCoverage do
    slather(
    input_format: "bah",
    scheme: "iOSFirstApp",
    proj: "iOSFirstApp.xcodeproj"
  )
    
#     xcov(
#   project: "iOSFirstApp.xcodeproj",
#   scheme: "iOSFirstApp",
#   output_directory: "xcov_output"
# )
  end
  
  desc "Linting"
  lane :lint do
    swiftlint()
  end
  
  desc "Description of what the lane does"
  lane :custom_lane do
    build_app(scheme: "iOSFirstApp",
    export_method: "validation",
     export_options: {
      destination: "upload"
      # provisioningProfiles: {
      #   "com.salma.iOSFirstApp" => "com.salma.iOSFirstApp"
      # }
    })
    firebase_app_distribution(
        app: "1:1023208811872:android:84d94bee0643fce0ed8205",
        service_credentials_file: "/Users/salmahassan/Study/Session/iosfirstapp-fe651-a5fe14f86fb9.json",
        groups: "test-fastlane",
        release_notes: "Lots of amazing new features to test out!"
      )
  end
end
